### ISSUE TITLE
Why the number of classes is 1 in training?

### ISSUE THREAD

**Issue by wytcsuch** [sentinelhq/face-x-ray#3]
Thank you very much for your codes. After generating face X ray, we need to judge whether it is real or fake. It should be a binary problem. Why do you set the number of classes to 1?  looking forward to your reply.

```
aux_params=dict(
            pooling='max',             # one of 'avg', 'max'
            dropout=0.5,               # dropout ratio, default is None
            activation='sigmoid',      # activation function, default is None
            classes=1,                 # define number of output labels
        )
        self.model = smp.DeepLabV3Plus(encoder_name="efficientnet-b6", encoder_weights="imagenet", in_channels=3, classes=1, aux_params=aux_params)
```

**Comment by zb-zuishuai** [comment]
when you test the ckpt,you will find the prediction of the picture  include mask and label,but the label just has one class

**Comment by zb-zuishuai** [comment]
mask虽然可以勉强预测，但是label只有单分类，我都不知道准确度怎么得的

**Comment by niladridutt** [comment]
Hi @wytcsuch @zb-zuishuai 
It's using a sigmoid activation function, thereby making it a binary classification problem.
It can have only one class in the mask since mask can only exist if the image is fake. Real images won't have a mask.

**Comment by zb-zuishuai** [comment]
Although the paper is focused on the generation of the mask, the label is the key to the accuracy. I can use the test set to output masks, but I can't output the labels.

**Comment by niladridutt** [comment]
@zb-zuishuai for real images, simply don't blend. The output mask will be a blank image and the corresponding label will be real. This is pretty straightforward and has already been implemented [here](https://github.com/nftport/face-x-ray/blob/e5813a27446f17c3f7a49a5c995cf57e28c80c9e/bi_online_generation.py#L63)
